version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=starwarsdb
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma123

  prisma:
    image: prismagraphql/prisma:1.17.0
    restart: always
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            database: starwarsdb
            schema: public
            user: prisma
            password: prisma123
            migrations: false
            ssl: false
